package com.nerisa.datarepo.ontology;

import org.apache.jena.rdf.model.*;
import org.apache.jena.ontology.*;

/**
 * Vocabulary definitions from /home/nerisa/Desktop/geo.rdfs
 *
 * @author Auto-generated by schemagen on 26 Mar 2018 15:01
 */
public class GeoSchema {
    /**
     * <p>The ontology model that holds the vocabulary terms</p>
     */
    private static final OntModel M_MODEL = ModelFactory.createOntologyModel(OntModelSpec.OWL_MEM, null);

    /**
     * <p>The namespace of the vocabulary as a string</p>
     */
    public static final String NS = "http://www.w3.org/2003/01/geo/wgs84_pos#";

    /**
     * <p>The namespace of the vocabulary as a string</p>
     *
     * @return namespace as String
     * @see #NS
     */
    public static String getURI() {
        return NS;
    }

    /**
     * <p>The namespace of the vocabulary as a resource</p>
     */
    public static final Resource NAMESPACE = M_MODEL.createResource(NS);

    public static final DatatypeProperty LAT = M_MODEL.createDatatypeProperty("http://www.w3.org/2003/01/geo/wgs84_pos#lat");

    public static final DatatypeProperty LONG = M_MODEL.createDatatypeProperty("http://www.w3.org/2003/01/geo/wgs84_pos#long");

    public static final OntClass POINT = M_MODEL.createClass("http://www.w3.org/2003/01/geo/wgs84_pos#Point");

    public static final OntClass SPATIAL_THING = M_MODEL.createClass("http://www.w3.org/2003/01/geo/wgs84_pos#SpatialThing");

}
